spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:20049/irondb
    username: root
    password: '{cipher}880fd2424b6fcfefdbe59a2c01b3393df1618d408250a3c435779eb43d9d8bef'
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
